### ISSUE TITLE
support for gnome-shell 40 

### ISSUE THREAD

**Issue by Muqtxdir** [Muqtxdir/yaru-remix#8]
Make _gnome-shell_ theme for **Gnome 40** based on Yaru-style 

### to-do:
- [x]  **Yaru-remix** (_see the demo-video_)

https://user-images.githubusercontent.com/54065734/109414021-a4379380-79d6-11eb-80c8-941c7fbbdd39.mp4

- [x] **Yaru-remix-dark** (_see the demo-video_)

https://user-images.githubusercontent.com/54065734/110242425-0fa3d700-7f7c-11eb-8081-10da0d2410ac.mp4

- [x] **Yaru-remix-light** (_see the demo-video_)

https://user-images.githubusercontent.com/54065734/110252863-78577780-7fad-11eb-830b-74093179f641.mp4

- [ ] modify **_install.sh_** and **_uninstall.sh_**
_Note: This is being applied on Fedora 34 builds in a virtual machine at the moment_

**Comment by Muqtxdir** [comment]
Will push a `gnome-40` branch soon.
